#web
server:
  port: 9100


spring:
  application:
    name: wzkris-monitor-admin
  profiles:
    # 环境配置
    active: @profiles.active@
  cloud:
    nacos:
      server-addr: @nacos.server@
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        namespace: @nacos.namespace@
        group: @nacos.group@
      config:
        namespace: @nacos.namespace@
        group: @nacos.group@
  config:
    import:
      - optional:nacos:common.yml?group=COMMON_GROUP
      - optional:nacos:${spring.application.name}.yml
