spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      username: dev
      password: nacos
      discovery:
        namespace: application-dev
        group: APPLICATION_GROUP
      config:
        namespace: application-dev
        group: APPLICATION_GROUP
  config:
    import:
      - optional:nacos:common.yml?group=COMMON_GROUP
      - optional:nacos:redis.yml?group=COMMON_GROUP
      - optional:nacos:thread.yml?group=COMMON_GROUP
      - optional:nacos:${spring.application.name}.yml

--- # xxl-job 配置
xxl.job:
  # 执行器开关
  enabled: false
  # 调度中心地址:如调度中心集群部署存在多个地址则用逗号分隔。
  admin-addresses: http://localhost:9200/xxl-job-admin
  # 执行器通讯TOKEN:非空时启用
  access-token: b469abd7-38d9-11ef-9ec3-00155d106729
  executor:
    # 执行器AppName:执行器心跳注册分组依据；为空则关闭自动注册
    appname: xxl-job-executor
    # 执行器端口号 执行器从9101开始往后写
    port: 9201
    # 执行器注册:默认IP:PORT
    address:
    # 执行器IP:默认自动获取IP
    ip:
    # 执行器运行日志文件存储磁盘路径
    logpath: ./logs/xxl-job
    # 执行器日志文件保存天数:大于3生效
    logretentiondays: 30
