#web
server:
  port: 8080
# Spring
spring:
  application:
    # 应用名称
    name: wzkris-gateway
  profiles:
    # 环境配置
    active: @profiles.active@
  cloud:
    nacos:
      # 注册地址
      server-addr: @nacos.server@
      #权限认证
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        namespace: @nacos.namespace@
        group: @nacos.group@
      config:
        namespace: @nacos.namespace@
        group: @nacos.group@
    sentinel:
      # 取消控制台懒加载
      eager: true
      transport:
        # 控制台地址
        dashboard: 127.0.0.1:8718
      # nacos配置持久化
      datasource:
        ds1:
          nacos:
            server-addr: @nacos.server@
            username: @nacos.username@
            password: @nacos.password@
            namespace: @nacos.namespace@
            groupId: @nacos.group@
            dataId: sentinel-gateway
            data-type: json
            rule-type: flow
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml