#web
server:
  port: 8080
  http2:
    enabled: true

spring:
  application:
    name: wzkris-gateway
  profiles:
    active: @profiles.active@
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/wzkris-auth-api