<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.wzkris</groupId>
        <artifactId>wzkris-gateway</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>wzkris-gateway-api</artifactId>

    <description>
        wzkris-gateway网关模块API
    </description>

    <dependencies>
        <dependency>
            <groupId>com.wzkris</groupId>
            <artifactId>wzkris-common-swagger</artifactId>
        </dependency>

        <dependency>
            <groupId>com.wzkris</groupId>
            <artifactId>wzkris-common-validator</artifactId>
        </dependency>

        <dependency>
            <groupId>com.wzkris</groupId>
            <artifactId>wzkris-common-remote</artifactId>
        </dependency>

        <dependency>
            <groupId>com.wzkris</groupId>
            <artifactId>wzkris-captcha-api</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>

</project>
